apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
type: Opaque
stringData:
  LAN_PREFIX: ENC[AES256_GCM,data:ek345zMqCbRWtbQ=,iv:jc+1gcKLxKkhJzxbgc9H7ixlotmWofxYii61n8WwxmQ=,tag:HksPRGdHiHUP8HDOUvNyIA==,type:str]
  EVCC_MODBUS_HOST: ENC[AES256_GCM,data:qFhC2F+Hmj/h4nXQAOY=,iv:c0LBo+l62br/jDKo/GoEZe66mpUAvp0H+Ul+M8Ptfjk=,tag:QH51cYsVPwrJnXAk744r1w==,type:str]
  ETCD_IP_1: ENC[AES256_GCM,data:Fnd7skGZKVkbLHxECg==,iv:mQlu2MbFVYy9hwjTi+hMbCuN3Db9Cu/p7SLsdHHNWyg=,tag:7d+Amkfs/vfSYUbPLr/sNQ==,type:str]
  ETCD_IP_2: ENC[AES256_GCM,data:UrmMDgSOTCqE838Ccg==,iv:EOcwMGRYUZz0DtYpsXQhXeN9qPORjucUlI5OCiKI1I8=,tag:86lYgMGO1vnzVVnrKt6EjQ==,type:str]
  ETCD_IP_3: ENC[AES256_GCM,data:eusClfQhZMJpjIzo4w==,iv:hUtgLySoKteVW8F4uTsPpoItNLXVePiUMqF5W5jl7Os=,tag:EdVHdAalIGUj+e2hOX+uCA==,type:str]
  ALERT_EMAIL_FROM: ENC[AES256_GCM,data:4rFHlI85wrX/eDeG,iv:cesJgKqf1ymFiR5qxXEPXnprZESi+yhyYKGJqUArJuQ=,tag:h2hYV26X4hWFFBpoOJ1gbA==,type:str]
  ALERT_EMAIL_TO: ENC[AES256_GCM,data:ydpZCaqMYRc/aYfq,iv:DOtMHx5JQ2WyGKd/TzTkUX7A/PtvHZZghYJFiDCjqYU=,tag:AlKZDHxepPHmLSCJqSSBuQ==,type:str]
  GATEWAY_DOMAIN: ENC[AES256_GCM,data:XAHDbHYVrw==,iv:7435N5EMBLE5pSWFfZExQTiI/yZhfon2IcaecUIBtGQ=,tag:6pVANS5mi3vTwnaEYukfeQ==,type:str]
sops:
  age:
    - recipient: age1j5qzs2enjury5s9zvgrwcggpnrfj3nkfm2qdzykjgg2kty6wga6qjgkpmz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZlE5a0V4bUJQcWNabDJo
        VHpncXZxclJwclBsYU9wYlFRMUYveld6MEJJCmphUkd0a3Q3WDdFcFNHWXQyUmVP
        RCtMWWhINGdOdUNNdDRGUUdnL2VOUVkKLS0tIERZUEVxS0hTSDhsdnJrNkQxSUht
        WTM1QW16NHJmaGRTb3liaHlJeTBvYzgK7466yOrgVzAe+lo+MWF0d0eXHrQxdyNo
        4dRM77YcZQJE44WNHIQnkM/eWyV9rZzh52danb/8bevtVHEjgo29VA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-14T17:55:01Z"
  mac: ENC[AES256_GCM,data:pZZPP7/wCT7g4/vZtVvOlsJR7YXLRj8X2zVYeSbKZV4wPS1TODzVu2br7PcowbgSUWN06/vnaBA0gSam1a7VFuw/fEcOhEz4XC+YVEhShxFRwZzGZeRz65ZQdl/lfLfcUAPHCFJhc1rHNRx592I+DmaD5J35OM0wu+snMRdlGoA=,iv:QwnlLrwEWy2P1FXvO7dChHUcgSblHUlVKtjoCRYgzD4=,tag:9Dg3bQm1/OTb0GNjR0FJhw==,type:str]
  encrypted_regex: ^(data|stringData|peerASN|peerAddress|localASN|cidr|email|.*\bhostname|dnsNames)$
  version: 3.11.0
