apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
type: Opaque
stringData:
  GATEWAY_DOMAIN: ENC[AES256_GCM,data:kac8WtTUOg==,iv:+5F9V0Q+miIrMyvXk4rbh2Dch8yAJNjfGV9X2BJ1lOg=,tag:TARr3C1nUknaoitUbaYVww==,type:str]
sops:
  age:
    - recipient: age1j5qzs2enjury5s9zvgrwcggpnrfj3nkfm2qdzykjgg2kty6wga6qjgkpmz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwU2hSSnEvVG13bjlTNFNN
        Ky9CVVdwb0tLTzZHQkxhZFkxU2habE13S0RFCkxsNWRzbjlVRXBjK1pZQnNUTWNC
        Qm9iM1U0VEZEWkxmYnpUOGVGb21tYlUKLS0tIEllTk03ajRaRVA3cDVBcEIxTEcv
        YWM1aDZoemdmOHhodTB4bkFPR3FPaVUKORYZly4kKnNQt4yG9hoVjbyYQZtA3kqE
        ZS/t0sE6o1GIKroeS1ZReupku7O4Up0sWHeqIBmOogrN7xSFcSeSTg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-13T15:38:30Z"
  mac: ENC[AES256_GCM,data:IgWDS27u8SG8ubG9+h6tb4Bv14AVVRSj/q78vSS873Xeq2IylG/O2y4jETDYJSeLLwTDF/NuQ40g0+j7VTNYh7ntnJEP+lebjea1e/LWlwg1ls2aNwEk1g7n1Kq5hnRZR334u6LyxZfoEOZyA966svNo8lDP4HvaQB2759ZzeWg=,iv:ldMpQdPlg3KIqU+qz5r90kUcHRMcPjSp8rNJm5N5M0U=,tag:Zl2NytQHDuT1pZomFmgeNA==,type:str]
  encrypted_regex: ^(data|stringData|peerASN|peerAddress|localASN|cidr|email|.*\bhostname|dnsNames)$
  version: 3.11.0
