apiVersion: v1
kind: Secret
metadata:
  name: evcc-env
  namespace: evcc
type: Opaque
stringData:
  EVCC_SPONSORTOKEN: ENC[AES256_GCM,data:WvzO6RmvSzRWRhD/wvromJmtpWiAxdNJdWKfKrLCUshjxGInTxkq7QVV9sPqqzAq+jnXuzk7swwGL4Vtgju3Di4ebDT/74GuzWe+vD4e39GoLanVWen9D8lEX7sdQR1+R5gK1SpN4wx1Hz3EhqPlUHE8UWOQTWwaQIjrpS1vuzRY2H8SF8Cm27y47i19qzqW/rjh7XSkmXyWXSdu67oxUtE4HqOxRvBZD+YZy4bkQj3DZ0F+2TgvxA==,iv:SoncqX+J2tjwa6Qr0x7XCJylxbYLIqj9U3srXvrxm6U=,tag:aNXfsPFiBvT1qQvrIIzwdg==,type:str]
  LITESTREAM_ACCESS_KEY_ID: ENC[AES256_GCM,data:L7G16JlHV4Gxv6coKEbzpf/SQ+8=,iv:5Cwe07Ex6dNQk4OlQW/CVG5YwgovVihO4gUt4DomlBs=,tag:HYQeJSCDe170Tu34DnL/Tg==,type:str]
  LITESTREAM_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:63PiI+WG/A6rOa/GBjC9PqVxTH7ul4tm7uORB9dLc67IpVYQFJz5kg==,iv:Z6mTXjE/s7lR77CyOSEPVhCFZ3ByZ04ib4W3ftKVlQY=,tag:gOVHFAz1n95vPZcUVYeXJg==,type:str]
sops:
  age:
    - recipient: age1j5qzs2enjury5s9zvgrwcggpnrfj3nkfm2qdzykjgg2kty6wga6qjgkpmz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSN0tMa3gzbVdPeUlySmx1
        NnA3SHh0bDhUcVZTbWtDd0tTOE0yODI3ZEJ3CnliUlN6eUF2OWJ0S2tTQTRicVhi
        WTNESXlmN0UzekhiQ3RzRldFcXFaTlEKLS0tIDZYSE1QaFJkUis1MHB4RGc2alUr
        L2dLcFhJWHdCaVhxYmlBWHZjOGZmMUUK8lzD5od3PwEN3TSW1ttSneZ2mJFZhj0/
        n3UAgyJS1/VJ/YShHXUHU8Askwrq3soOBiNxKXjxKA9NW5tHteX8Fw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-13T16:02:00Z"
  mac: ENC[AES256_GCM,data:pTGw4S3vGswgIy4fAU4j0HjEA+3cnRs3IT03aeTwQjfBw/1G1o5ZPYl+iPdFLr0wjzQdjU6gDSNOUqsnNrlBcaOL84c7XNaMaOtmcLzEj2J8v38HKJVqXVOd/X7NcioDdC5H0UwTtpyHFiP3Mxx+A9H12BHvkzC+OLvTZopMVdM=,iv:kiMiFx/o/i5Af2pIrDXhwGu2aGDPHldp9/zDo0EUk5Q=,tag:JdeLWPbLgaiFBjm3M1QEfQ==,type:str]
  encrypted_regex: ^(data|stringData|peerASN|peerAddress|localASN|cidr|email|.*\bhostname|dnsNames)$
  version: 3.11.0
