apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    certmanager.io/issuer: letsencrypt
  labels:
    public: "true"
  name: cilium
  namespace: gateway-default
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "*.${GATEWAY_DOMAIN}"
    labels:
      advertise: bgp
      public: "false"
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      hostname: "*.${GATEWAY_DOMAIN}"
      name: http
      port: 80
      protocol: HTTP
    - allowedRoutes:
        namespaces:
          from: All
      hostname: "*.${GATEWAY_DOMAIN}"
      name: https
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ""
            kind: Secret
            name: wildcard-tls
        mode: Terminate
