apiVersion: v1
kind: Secret
metadata:
    name: demo-credentials
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:xK3MrgI=,iv:KcwK+qajp7P4GShQQlpTel/9r27MOoApuUHyP+SBn1U=,tag:9WYoRCRDQa2FEkq2SFe23w==,type:str]
    password: ENC[AES256_GCM,data:QlIEBD0=,iv:FVNQ2v4JsWSDZOpGsXDPglMHGJfmPBbxjYnY7N3M02k=,tag:o4p4CtXJuwiYmVI7mrzVRg==,type:str]
sops:
    age:
        - recipient: age1j5qzs2enjury5s9zvgrwcggpnrfj3nkfm2qdzykjgg2kty6wga6qjgkpmz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVVZ5Z29zU3diNjdTc01K
            V3lvMk1mNTQ2cmdjdkJQMjA2YllhQXREUWxNCndTQXo2cXd2Uk5vT2pwWnVrc1pz
            cS9iK2lHU1pBOWpoM2szR0ttaVNsa1EKLS0tIGNibWtVdlJJaFdhdkdOWWJ1dUt2
            by9zTFpzb25ObitVUTR4WDVHdGRYQ28KTrZT0Th6lEJjQkDWZF05sUy2pOxornGh
            kAPOOzjJHUH0PLQN3gM47kHdjWYL+yTrS/q8VziyC1boL6qhfZ1hfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T14:26:07Z"
    mac: ENC[AES256_GCM,data:RSRXj/z0wgS6CIauvOdEfM0XoXqhYbVs1n36bzwo6G+UFFF94hw24N40guIxXftFjdJwFDq6C4sGblMPzHwZ0Us1gxdWpBivcoSw6umIHeU2EsofN0fw+8mYFiIjTmDiqrTBsRfwKi7vRGMuJeptjZOfwQTMD+zYleiaG6MNBmQ=,iv:3SFB/qOOthtdh2ZLLDYv4iGwUgF06XUeOi750cSOISk=,tag:dgknNcnQtK87Ey4ZDxlOsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
