apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./secrets.yaml
  - ./authelia-values.yaml
  - ./configmap-litestream-lldap.yaml
  - ./configmap-litestream-authelia.yaml
  - ./sts-ldap.yaml
  - ./service-ldap.yaml
  - ./httproute-ldap.yaml
  - ./helmrelease-authelia.yaml
