apiVersion: v1
kind: Secret
metadata:
  name: sso-secrets
  namespace: sso
type: Opaque
stringData:
  LLDAP_JWT_SECRET: ENC[AES256_GCM,data:GwzDRESMG7ZV+3sU+RfZOrDG4vlppm7YaDieWsOg7AI=,iv:xe7nCpcLCjhqP+iRQUY2flETRfNYTS4tPKgEr8kpiec=,tag:OAmgbRirPEryI71Qrko8/A==,type:str]
  LLDAP_KEY_SEED: ENC[AES256_GCM,data:J5rlJACFySbj2QEBl0yIvIIDBjry9okMC9/O/r0drAg=,iv:5LlUnkJnl9TGvR4KfkAkHeeRhUjcWPwlMW1OZl2fdLY=,tag:f7p6Lfy+mbVkcwSGiFQDoQ==,type:str]
  LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:tre0fB+ckFoudgyM,iv:qwjyqaxII0lTpxlQlarNDnThc8yblTHOCLIGw5jhUcg=,tag:eIg/AZFjqV+fLzVsmtwO2Q==,type:str]
  LITESTREAM_ACCESS_KEY_ID: ENC[AES256_GCM,data:9pp3icstuApNsJp4+FwVgYM76gY=,iv:6Ol7k+cXEDwpWkM9GBBYx6YRMFW9MiUeStfbrhSh4is=,tag:ujuu9BNPgLV7ZkjqUdFRGQ==,type:str]
  LITESTREAM_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:zZvP4ZHn/nrIDcReu+ibeHLPe8f+MDBjnVWThzJWDg2hPY1WXsztEw==,iv:xvzBNnSVZeLag1hCZ3GWHPc0ZxAzz/PTjkW0p3KPfjg=,tag:xOR5SJeEhXwi1esHeDTrWw==,type:str]
sops:
  age:
    - recipient: age1j5qzs2enjury5s9zvgrwcggpnrfj3nkfm2qdzykjgg2kty6wga6qjgkpmz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVURTSUdJcmdNelZyVGw5
        K1djdVBRazlpbHR4Um14Y3piRXhicG82WkVjCktGTGpOdkxMeEVySy9KOE4vaytT
        dWc3TnFPT2JKaWdoTXcra1J6NDkzRzgKLS0tIGNVWWE2VzlYSkdFdllWWXpHWUV5
        RjdUK1RWMmdmYm1YSGF1bDNpUDdlWE0KkV9tZT/nxrAofh1ILKS2+BFRAfnVEbRQ
        /TpxW/Nacv86FYdPtKrnE8hkLMaXnAAkF5kHHad1DOdM8ihjrvmKsA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-13T18:24:03Z"
  mac: ENC[AES256_GCM,data:okR3PgWnpqVBTC+NkPlhC+D2uww+VXb90h5C8G7+QP+usjw+HScjdekUndQMWQxe1FTpZDlkdTPjO0+3bZQaZ3YSE7tcwjMTw1O9c6HeYU/JVdwFMRR9Qp0wX1olRAuWCVxpxnNEz9IsvJTQ6jQWIhOPhcpjLjO/mfmzQX2LlTI=,iv:ChnDT/nwBs5XYmcbDf1ZZ346uJ1pugk09yca5JfV9HE=,tag:Vk6LFZo/8k97zXEla8UaCg==,type:str]
  encrypted_regex: ^(data|stringData|peerASN|peerAddress|localASN|cidr|email|.*\bhostname|dnsNames)$
  version: 3.11.0
