upgradeCompatibility: "1.18"
ipv6:
  enabled: true
ipam:
  mode: kubernetes
operator:
  enabled: true
  replicas: 2
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
envoy:
  enabled: true
  securityContext:
    capabilities:
      keepCapNetBindService: true
      envoy:
        - NET_BIND_SERVICE
        - NET_ADMIN
        - SYS_ADMIN
bpf:
  hostLegacyRouting: true
bgpControlPlane:
  enabled: true
l2announcements:
  enbled: false
kubeProxyReplacement: true
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
cgroup:
  autoMount:
    enabled: true
  hostRoot: /sys/fs/cgroup
k8s:
  requireIPv4PodCIDR: true
k8sServiceHost: localhost
k8sServicePort: 7445
gatewayAPI:
  enabled: true
  enableAlpn: true
  enableAppProtocol: true
  service:
    externalTrafficPolicy: "Cluster"
cni:
  # required for multus to work
  exclusive: false
