apiVersion: v1
kind: ConfigMap
metadata:
  name: mealie-litestream-config
  namespace: mealie
data:
  litestream.yml: |
    addr: :9090
    dbs:
      - path: /app/data/mealie.db
        replicas:
          - type: s3
            bucket: backup.f9k.dev
            path: mealie
            endpoint: https://s3.eu-central-2.wasabisys.com
  restic-ignore.txt: |
    backups
    mealie.db
    mealie.db-*
    .mealie.db-*
    lost+found
    mealie.log
    mealie.log.*
