apiVersion: v1
kind: Secret
metadata:
  name: mealie-secrets
  namespace: mealie
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:4mDVW0CZCUnN4gxlyty4C4kfDhQ=,iv:bliTXNAc1K8MbVFVyOXiTzZXq1wNYMbp5tZcScSYBAw=,tag:H6ddPqewh9Gp599WxVNWxQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:KqcsFcEX1bxCua9lsDljmrzJl0KwgT2eDzhZRA6+35MoDjtsjtocOw==,iv:w8WBk4F2G6bnsi5DGJ4VZhlawDJ7hyByHCwnZrJAz2w=,tag:Rbku3caFNRpDYEbm8ts7fA==,type:str]
  LITESTREAM_ACCESS_KEY_ID: ENC[AES256_GCM,data:5j3932m9IyN/T4HKUZkIPzUJEQg=,iv:tMqGk455cbH68SO+PTaMtrMN7oWB67qVkVv8kgCmWA4=,tag:6pV4bTVEwZbjGJHd3JknAQ==,type:str]
  LITESTREAM_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:rsGsNFiYcHiHbDXRxYc/CETPEdPDqBkPZYQU3j8YBbIhpAUDQhxZaw==,iv:s0qiV1BGNOw5/PG0GRveFIISyGrmqFDK1UykLaLAzjI=,tag:eKkOslKxqVDy59TijmLzJQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:AmD5A4uO3IZdo8XqJwytyrM=,iv:R/Q6tE3aMnK+QSnyEtihb0R7wyBB8qR2uTMlVqcrCRg=,tag:bV2h5TN04u1YAscB7H27/A==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:5U57bOEg1VByRMU3vodGIPWJaDRwpKl65c+xLmGx/3SDnf4sVOBRhsH4hOFe6exNkMt+giXdsIg2/OZQ+IXgmg==,iv:0vPiWwh8TagI81P7biPNPcPdS/6fcTDq3eXslgKyl+k=,tag:ucx+OnQWsulbTUxms8AsNA==,type:str]
sops:
  age:
    - recipient: age1j5qzs2enjury5s9zvgrwcggpnrfj3nkfm2qdzykjgg2kty6wga6qjgkpmz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcmJlcGJlQ1F2cVhwNFhV
        SmZYQlVEa0dUT09xc1N6QjdtNk1sT1hMbkIwCkJpNS9TRVFhZjZVTzJhNkZlR2lt
        RGlEMysxRTVYWVMxMGRPbHVrVHVtQ2cKLS0tIHlQdzVTdlBNeS81Sk1ZQ2VhcVls
        b1RtRVdwck5mK2dqa1RYd0p1a3JKTlkK2qUa2BQgby0Hrggt0NCx0zlqv4pcUmct
        LL09hTjirLcEvpOQVovjIlTfKNG0xFKjTq+cIKhvrKoyorSN0L2t2Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-13T18:38:30Z"
  mac: ENC[AES256_GCM,data:EoBsFrTIv2aHdd/zWq4zPuZ+8hu8zUBQQnDcOVMQFrxmGN4mf1XgvLonTeWsOS/FGWzmeyTnWoHHAmE44IVtJNbCzR/xBtY9odlWPpqKsLETpzEPqtScIFwWJNz3xyne2oOg2QNbp+LNEuNrdY1y0Slrss6h6OqOfe68k+ogqnU=,iv:hOajz/XdpySaPWJrgI1YdApvdTKDfOO8dcTI95UWSP8=,tag:bHbKfIa5epgoIYJdafPeEw==,type:str]
  encrypted_regex: ^(data|stringData|peerASN|peerAddress|localASN|cidr|email|.*\bhostname|dnsNames)$
  version: 3.11.0
