apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: smarthome
  labels:
    app: mosquitto
    # selects the internal CiliumLoadBalancerIPPool that grants ${MQTT_LB_IP}
    public: "false"
    # advertises the LB IP over BGP
    advertise: bgp
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mqtt.${GATEWAY_DOMAIN}
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  ipFamilyPolicy: PreferDualStack
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
