apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wg-easy
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-cilium
    - name: infra-longhorn
  interval: 1h
  prune: true
  path: ./apps/wg-easy
  sourceRef:
    kind: GitRepository
    name: flux-system
