apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./infra-secrets.yaml
  - ./infra-sources.yaml
  - ./infra-cilium.yaml
  - ./infra-cilium-config.yaml
  - ./infra-gateway-api.yaml
  - ./infra-multus.yaml
  - ./infra-multus-config.yaml
  - ./infra-cert-manager.yaml
  - ./infra-cert-manager-config.yaml
  - ./infra-external-dns.yaml
  - ./infra-gateway.yaml
  - ./infra-kyverno.yaml
  - ./infra-longhorn.yaml
  - ./infra-generic-device-plugin.yaml
  - ./apps-wg-easy.yaml
  - ./apps-doko.yaml
  - ./apps-evcc.yaml
  - ./apps-mailer.yaml
