apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
data:
  api-token: ENC[AES256_GCM,data:l+UchhY0tzGEh2lR13Tovkhf+QSi86J0tiTwmTe4NAA27SKjVPUDbiEjw/Ts64l8zzciTT90HxI=,iv:3QFis0LvJOS8Ke/mdmpFkEIHhgLypAn35t8UWa08zSc=,tag:8tS3JANI0vn82QIz0kC9OQ==,type:str]
sops:
  age:
    - recipient: age1j5qzs2enjury5s9zvgrwcggpnrfj3nkfm2qdzykjgg2kty6wga6qjgkpmz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtK2tRaWU5UUhaWEZzbU1v
        WlA0d1JvWmJHcURiU3c0dm5ZYVhxZ3VXa3pFCnkxMHFVNzlVeVpwTklNeEFrVmRs
        THF0YnBIS21yZWJFUFEwNHNhMnZoeFkKLS0tIGFBUndDTHZNaXUxNHNaMW9uaFYx
        WFljOVRuU0Z4d3REb3RhbkZwbEZxeU0KNw9DqZxli3PQkRn6uupPn4rTXoeXSjMg
        NodKJRkVTmhyqqtdnbRzfcN+e862nF3uwhwCBFgR9GyDMSufLnT1fQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T22:29:03Z"
  mac: ENC[AES256_GCM,data:AiAOQqHjSPo4DwAJjVJEceBruSgelvMKjLpNDG7t0jYkUAGRSQowrzQY/8UdTpMZ5+5H/q6YKmcsRVzXgf7ZMbGZJ4QGoeLYylRnQA56/zfILt66NHwwIgdnGEXH1fLId05hoUlGd9xpJjYDX2JgJfqOp6pD9Fps2ASrcTQYpLA=,iv:o5y+Nn1DjXO1XbBiZBEaVnjavomfeDFoJF7eGfYkfI4=,tag:ZggUnOIieEoG2aNW62B8Zw==,type:str]
  encrypted_regex: ^(data|stringData|peerASN|peerAddress|localASN|cidr|email)$
  version: 3.11.0
