apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./secrets.yaml
  - ./configmap.yaml
  - ./pvc.yaml
  - ./sts-homeassistant.yaml
  - ./sts-node-red.yaml
  - ./sts-matter.yaml
  - ./service.yaml
  - ./http-route.yaml
