apiVersion: v1
kind: Secret
metadata:
  name: homeassistant-secrets
  namespace: homeassistant
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:1ZwBsiDU2OaFc0dCniMQNXpMiWI=,iv:wBt/w1FLZb6EpvwKcVcmS5oWGsV11PQnrKoDCjYcU6Q=,tag:G5N54FYSN3xqwHf1bTa2XQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:3bHL1XRTyjwOrWFt1XrhArO1pcrBdQ4wGgDvRSYuOQWSSm+pImQNPw==,iv:cbNb49MzTFOVT2RjsTtZ5y81LCz/1g+9x1iftgHFqTI=,tag:Vl7grsjVgU1uyhIRUvDDmw==,type:str]
  LITESTREAM_ACCESS_KEY_ID: ENC[AES256_GCM,data:rrQxhOEP8vKn264G5pHw6yksM+8=,iv:m/bKWq4alW1Pc5kruE+1X8QoLGhn6LYUwYjqbrJ6cWw=,tag:UNSqmtsG6WnYl4kMe8MZBw==,type:str]
  LITESTREAM_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:LMeHoL3Epo9PuM6/NayCSaJ8QLISa0KFHaDrp+bDEinvEUuYG3/vLw==,iv:Qo++XxxQKRXKeHlRqK9yvw5vXtvcPitomAjyAK2SmiI=,tag:u50A/IxeqyjdGGYswVQMxg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:kp8jHVO9rIWguQONUY8hhYE=,iv:+pVMlL51hdPs20wjHUt4kd2ny0nDEBmXTaJLsrl5eno=,tag:YkoB8MlzUfQatx8Rr7l+6w==,type:str]
sops:
  age:
    - recipient: age1j5qzs2enjury5s9zvgrwcggpnrfj3nkfm2qdzykjgg2kty6wga6qjgkpmz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMUtSUXVBQ0l4dXFWVWNh
        aUZDSTU3MzdwT2ZWUlc1WVVKYStrUW9wK204CmpJalZwRGxBQytKT1hNemVRbmxn
        T1cvVnQ0cWdzTGhUanBRdVRpWWlsc0EKLS0tIHgvNzJnZFVteFpsd2dPVXJCU0l4
        WGNSdVBHemlCWG5MRkNZZ2R0UzBsVncKDkAPL/8CE+oac5eVFOjMWa7sJRb2hdGn
        bchRRpP0+CL78t25m/jifRU+NlgV3tbVnsqb0NkReMZ2tGpQ7sVG5Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-13T17:16:44Z"
  mac: ENC[AES256_GCM,data:Fbdip6fMuWIX63LWosV0RHhRtdb1d9TcV3STtUQddqKS1lCucJaecgSBgHtutWNNoVJYNnqrnuI3cvplyH/0m6JlKI3Sn7AxJEn7cFaLkLl2oi7BSA78fFY/6lEpeKhs+hQcLu+3dXyV1jXJufpPMGMAn3K6WJelr6OT/vSUsvI=,iv:9LnkPV48ObxyVc0fGXPgDqW0QYHi1NJfbNCCnMcXJYc=,tag:gk0wPeuw3BPzdVfnAmCpkw==,type:str]
  encrypted_regex: ^(data|stringData|peerASN|peerAddress|localASN|cidr|email|.*\bhostname|dnsNames)$
  version: 3.11.0
