apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./crd.yaml
  - ./cluster-role.yaml
  - ./cluster-role-binding.yaml
  - ./service-account.yaml
  - ./config-map.yaml
  - ./daemon-set.yaml
  - ./dhcp-ds.yaml
