apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: global-ca-bundle
  namespace: cert-manager
spec:
  sources:
    - secret:
        name: internal-ca-secret
        key: ca.crt
  target:
    configMap:
      key: ca.crt
    namespaceSelector:
      matchLabels: {}
