apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
data:
  api-token: ENC[AES256_GCM,data:l+UchhY0tzGEh2lR13Tovkhf+QSi86J0tiTwmTe4NAA27SKjVPUDbiEjw/Ts64l8zzciTT90HxI=,iv:3QFis0LvJOS8Ke/mdmpFkEIHhgLypAn35t8UWa08zSc=,tag:8tS3JANI0vn82QIz0kC9OQ==,type:str]
sops:
  age:
    - recipient: age1j5qzs2enjury5s9zvgrwcggpnrfj3nkfm2qdzykjgg2kty6wga6qjgkpmz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtK2tRaWU5UUhaWEZzbU1v
        WlA0d1JvWmJHcURiU3c0dm5ZYVhxZ3VXa3pFCnkxMHFVNzlVeVpwTklNeEFrVmRs
        THF0YnBIS21yZWJFUFEwNHNhMnZoeFkKLS0tIGFBUndDTHZNaXUxNHNaMW9uaFYx
        WFljOVRuU0Z4d3REb3RhbkZwbEZxeU0KNw9DqZxli3PQkRn6uupPn4rTXoeXSjMg
        NodKJRkVTmhyqqtdnbRzfcN+e862nF3uwhwCBFgR9GyDMSufLnT1fQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T22:10:47Z"
  mac: ENC[AES256_GCM,data:gKleLFThZxd2ToVohXmHwcdRjrnuhBBeOR8NlNMXdCfPcBdo8OI7LNcj3yr+N1LVYeITjj3NyejmJ3n+jfE7ObALdQLSG/ULzXU/7hqYu/qfq4o8I5cbNiiFYDmX8MfQD7bsg5tZwFnDF3s5ZR5kY4TLrlmR9sZ4Rw/Qbl2hnBs=,iv:uJqRvPhdxIQitfdbBXZQV+7chO6COIiz5kgHMdLSF1M=,tag:+5uoiUMhv4lf03CKMhkOfg==,type:str]
  encrypted_regex: ^(data|stringData|peerASN|peerAddress|localASN|cidr|email)$
  version: 3.11.0
