apiVersion: v1
kind: Service
metadata:
  name: wg-easy-ui
  namespace: wg-easy
  labels:
    app.kubernetes.io/name: wg-easy
spec:
  type: ClusterIP # Change to NodePort or LoadBalancer if you want direct public access (risky)
  selector:
    app.kubernetes.io/name: wg-easy
  ports:
    - name: http
      protocol: TCP
      port: 51821
      targetPort: 51821
