apiVersion: v1
kind: Secret
metadata:
  name: relay-credentials
  namespace: mailer
type: Opaque
stringData:
  user: ENC[AES256_GCM,data:ZYgCzxyQYqWy6PXmwQp3Qg==,iv:INtZzCMmoNAETOL11rnOZPRJJYDSCdySw6Fl3JgdI5U=,tag:nbNnTE7fKD8DcHmPciIEBw==,type:str]
  password: ENC[AES256_GCM,data:y5bqncmMVUDltn/nBjuZQkAMvg==,iv:++02mFU8i5SYV0gz77aqsrd/AEXt26jPWp312C7anx4=,tag:R+6oZ8Um/9RwCuT3mpdGnw==,type:str]
sops:
  age:
    - recipient: age1j5qzs2enjury5s9zvgrwcggpnrfj3nkfm2qdzykjgg2kty6wga6qjgkpmz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQ1gzdlpIT2djSTRZZFBH
        MFI5WGlLTkJYUlJRTHhwUG91OEYyamZCa0ZRCm11SVE5WkU3eU5JL0g5VTd1OGxD
        eTU0ZzBkTE5GMVFlbnRQZm82ME51NFEKLS0tIG13MGxEY1lXM2RkdTdGQmZFNmFM
        YzRuVWJEMU9WVE5ENk5wWjVSaVlvdG8KEkzDLAZVM1Gli2UlQRGhnsXXPiqJL+Ea
        F6tuOAGiiyJSC2p0mTwNVxFx7mBPcOJNFPSwYtHNpO1sAX0H47AL2g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-13T16:37:59Z"
  mac: ENC[AES256_GCM,data:6EGss+JoZBrVL/QsLdwy+11H+nRaC2bRuHm4ZhNYDke+4mvqO5GFAlGcwqk9FykPvq8uc+NipB2yOv/S+nOkaNkqB5oQ74LBZz5SGmU3roF8LDYnFsP2IMNqkMrmcVoKq0BSw+rv7+1xFsYEdfy7iOuW9Xv5vX2TeSRSNfMC/XU=,iv:hC2p5orL28YRk0vwh93oVHjxydf3PjoB9GxNxGFHx1M=,tag:OntBq77Nsmk5zf1liV5eYw==,type:str]
  encrypted_regex: ^(data|stringData|peerASN|peerAddress|localASN|cidr|email|.*\bhostname|dnsNames)$
  version: 3.11.0
