apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./grafana-pvc.yaml
  - ./release.yaml
  - ./podmonitor-litestream.yaml
  - ./servicemonitor-longhorn.yaml
  - ./grafana-route.yaml
